<?php
// database/seeders/PageSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PageSeeder extends Seeder
{
  public function run(): void
  {
    $pages = [
      // Top-level pages
      [
        'parent_id' => null,
        'slug' => 'home',
        'name' => 'Home',
        'title' => 'Home | DUS - Dwip Unnayan Society',
        'description' => 'Empowering communities through sustainable development',
        'keywords' => 'NGO, development, Bangladesh, community empowerment',
        'og_image' => null,
        'template' => 'dynamic',
        'page_type' => 'regular',
        'is_published' => true,
        'published_at' => now(),
        'created_by' => null,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'parent_id' => null,
        'slug' => 'about',
        'name' => 'About Us',
        'title' => 'About Us | DUS - Dwip Unnayan Society',
        'description' => 'Learn about our mission, vision, and impact',
        'keywords' => 'about DUS, mission, vision, NGO Bangladesh',
        'og_image' => null,
        'template' => 'dynamic',
        'page_type' => 'regular',
        'is_published' => true,
        'published_at' => now(),
        'created_by' => null,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'parent_id' => null,
        'slug' => 'contact',
        'name' => 'Contact Us',
        'title' => 'Contact Us | DUS - Dwip Unnayan Society',
        'description' => 'Get in touch with us',
        'keywords' => 'contact DUS, address, phone, email',
        'og_image' => null,
        'template' => 'dynamic',
        'page_type' => 'regular',
        'is_published' => true,
        'published_at' => now(),
        'created_by' => null,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'parent_id' => null,
        'slug' => 'blogs',
        'name' => 'Blogs',
        'title' => 'Blogs | DUS - Dwip Unnayan Society',
        'description' => 'Latest news and stories',
        'keywords' => 'blog, news, stories, DUS',
        'og_image' => null,
        'template' => 'dynamic',
        'page_type' => 'blog',
        'is_published' => true,
        'published_at' => now(),
        'created_by' => null,
        'created_at' => now(),
        'updated_at' => now(),
      ],
      [
        'parent_id' => null,
        'slug' => 'projects-programs',
        'name' => 'Projects & Programs',
        'title' => 'Projects & Programs | DUS - Dwip Unnayan Society',
        'description' => 'Our development programs and initiatives',
        'keywords' => 'projects, programs, microfinance, climate change',
        'og_image' => null,
        'template' => 'dynamic',
        'page_type' => 'regular',
        'is_published' => true,
        'published_at' => now(),
        'created_by' => null,
        'created_at' => now(),
        'updated_at' => now(),
      ],
    ];

    DB::table('pages')->insert($pages);

    // Get the about page
    $aboutPage = DB::table('pages')->where('slug', 'about')->whereNull('parent_id')->first();

    if ($aboutPage) {
      $aboutChildren = [
        [
          'parent_id' => $aboutPage->id,
          'slug' => 'vision-mission',
          'name' => 'Vision Mission',
          'title' => 'Vision, Mission, Goal, Objectives and Core values | DUS - Dwip Unnayan Society',
          'description' => 'Vision, mission, goal, objectives and core values',
          'keywords' => 'vision, mission, goals, objectives, core values',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'about_sub',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $aboutPage->id,
          'slug' => 'functions',
          'name' => 'Background and Functions',
          'title' => 'Background, Roles and Functions | DUS - Dwip Unnayan Society',
          'description' => 'Background, roles and functions',
          'keywords' => 'background, functions, roles, history',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'about_sub',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $aboutPage->id,
          'slug' => 'legal-affiliations',
          'name' => 'Legal Status',
          'title' => 'Legal Status and Organizational Affiliations | DUS - Dwip Unnayan Society',
          'description' => 'Legal status and organizational affiliations',
          'keywords' => 'legal status, affiliations, registration',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'about_sub',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $aboutPage->id,
          'slug' => 'interventional-approaches',
          'name' => 'Interventional Approaches',
          'title' => 'Interventional Approaches and DUS Priorities | DUS - Dwip Unnayan Society',
          'description' => 'Interventional approaches and priorities',
          'keywords' => 'interventional approaches, priorities, strategies',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'about_sub',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $aboutPage->id,
          'slug' => 'evolutionary-changes',
          'name' => 'Evolutionary Changes',
          'title' => 'Evolutionary Changes and Footings | DUS - Dwip Unnayan Society',
          'description' => 'Evolutionary changes and footings',
          'keywords' => 'history, evolution, timeline',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'about_sub',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $aboutPage->id,
          'slug' => 'governance',
          'name' => 'Governance',
          'title' => 'Governance Structure | DUS - Dwip Unnayan Society',
          'description' => 'Governance structure',
          'keywords' => 'governance, executive committee, general body',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'about_sub',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $aboutPage->id,
          'slug' => 'operational-areas',
          'name' => 'Operational Areas',
          'title' => 'Operational Areas of DUS | DUS - Dwip Unnayan Society',
          'description' => 'Operational areas of DUS',
          'keywords' => 'operational areas, coverage, locations',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'about_sub',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $aboutPage->id,
          'slug' => 'achievements',
          'name' => 'Achievements',
          'title' => 'Our Achievements | DUS - Dwip Unnayan Society',
          'description' => 'Our achievements',
          'keywords' => 'achievements, milestones, success',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'about_sub',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $aboutPage->id,
          'slug' => 'programs-activities',
          'name' => 'Programs and Activities',
          'title' => 'Programs & Activities | DUS - Dwip Unnayan Society',
          'description' => 'Programs and activities',
          'keywords' => 'programs, activities, microfinance, jagoron',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'about_sub',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $aboutPage->id,
          'slug' => 'facilities',
          'name' => 'Facilities',
          'title' => 'Training and Other Facilities | DUS - Dwip Unnayan Society',
          'description' => 'Training and other facilities',
          'keywords' => 'training, facilities, capacity building',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'about_sub',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
      ];

      DB::table('pages')->insert($aboutChildren);
    }

    // Get the blogs page
    $blogsPage = DB::table('pages')->where('slug', 'blogs')->whereNull('parent_id')->first();

    if ($blogsPage) {
      $blogChildren = [
        [
          'parent_id' => $blogsPage->id,
          'slug' => 'invest-in-kindness-reap-a-better-future',
          'name' => 'Invest in Kindness, Reap a Better Future',
          'title' => 'Invest in Kindness, Reap a Better Future | DUS - Dwip Unnayan Society',
          'description' => 'Blog post about kindness and future impact',
          'keywords' => 'kindness, future, investment, microfinance',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'blog',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $blogsPage->id,
          'slug' => 'how-technology-is-changing-education',
          'name' => 'How Technology is Changing Education',
          'title' => 'How Technology is Changing Education | DUS - Dwip Unnayan Society',
          'description' => 'Blog post about technology and education',
          'keywords' => 'technology, education, digital learning',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'blog',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $blogsPage->id,
          'slug' => 'sustainable-living',
          'name' => 'Sustainable Living',
          'title' => 'Sustainable Living: Small Changes, Big Impact | DUS - Dwip Unnayan Society',
          'description' => 'Blog post about sustainable living',
          'keywords' => 'sustainability, environment, lifestyle',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'blog',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $blogsPage->id,
          'slug' => 'future-of-remote-work',
          'name' => 'Future of Remote Work',
          'title' => 'The Future of Remote Work | DUS - Dwip Unnayan Society',
          'description' => 'Blog post about the future of remote work',
          'keywords' => 'remote work, future, technology',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'blog',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $blogsPage->id,
          'slug' => 'mental-health-awareness-in-the-workplace',
          'name' => 'Mental Health Awareness in the Workplace',
          'title' => 'Mental Health Awareness in the Workplace | DUS - Dwip Unnayan Society',
          'description' => 'Blog post about mental health awareness',
          'keywords' => 'mental health, workplace, wellness',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'blog',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $blogsPage->id,
          'slug' => 'innovations-in-renewable-energy',
          'name' => 'Innovations in Renewable Energy',
          'title' => 'Innovations in Renewable Energy | DUS - Dwip Unnayan Society',
          'description' => 'Blog post about renewable energy innovations',
          'keywords' => 'renewable energy, innovation, sustainability',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'blog',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $blogsPage->id,
          'slug' => 'building-a-personal-brand-online',
          'name' => 'Building a Personal Brand Online',
          'title' => 'Building a Personal Brand Online | DUS - Dwip Unnayan Society',
          'description' => 'Blog post about personal branding',
          'keywords' => 'personal brand, online, marketing',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'blog',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $blogsPage->id,
          'slug' => 'the-art-of-effective-communication',
          'name' => 'The Art of Effective Communication',
          'title' => 'The Art of Effective Communication | DUS - Dwip Unnayan Society',
          'description' => 'Blog post about effective communication',
          'keywords' => 'communication, skills, leadership',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'blog',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $blogsPage->id,
          'slug' => 'financial-planning-for-young-professionals',
          'name' => 'Financial Planning for Young Professionals',
          'title' => 'Financial Planning for Young Professionals | DUS - Dwip Unnayan Society',
          'description' => 'Blog post about financial planning',
          'keywords' => 'finance, planning, career',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'blog',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $blogsPage->id,
          'slug' => 'tech-is-changing-the-world',
          'name' => 'Tech is Changing the World',
          'title' => 'Tech is Changing the World | DUS - Dwip Unnayan Society',
          'description' => 'Blog post about technology changing the world',
          'keywords' => 'technology, innovation, future',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'blog',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
      ];

      DB::table('pages')->insert($blogChildren);
    }

    // Get the projects page
    $projectsPage = DB::table('pages')->where('slug', 'projects-programs')->whereNull('parent_id')->first();

    if ($projectsPage) {
      $programChildren = [
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'micro-finance',
          'name' => 'Micro-Finance Program',
          'title' => 'Micro-Finance Program | DUS - Dwip Unnayan Society',
          'description' => 'Micro-finance program details',
          'keywords' => 'microfinance, micro-credit, PKSF, savings',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'climate-change',
          'name' => 'Climate Change and Disaster Management',
          'title' => 'Climate Change and Disaster Management | DUS - Dwip Unnayan Society',
          'description' => 'Climate change and disaster management program details',
          'keywords' => 'climate change, disaster management, coastal resilience',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'community-radio',
          'name' => 'Community Radio',
          'title' => 'Community Radio | DUS - Dwip Unnayan Society',
          'description' => 'Community radio program details',
          'keywords' => 'community radio, voice for change, Hatiya',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'dwip-education',
          'name' => 'DWIP Education Program',
          'title' => 'DWIP Education Program | DUS - Dwip Unnayan Society',
          'description' => 'Education program details',
          'keywords' => 'education, scholarship, children, literacy',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'information-and-communication-technology',
          'name' => 'Information and Communication Technology',
          'title' => 'ICT for Development | DUS - Dwip Unnayan Society',
          'description' => 'ICT program details',
          'keywords' => 'ICT, digital literacy, technology',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'research-and-documentation',
          'name' => 'Research and Documentation',
          'title' => 'Research and Documentation | DUS - Dwip Unnayan Society',
          'description' => 'Research and documentation program details',
          'keywords' => 'research, documentation, surveys, impact assessment',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'livelihood-restoration-project',
          'name' => 'Livelihood Restoration Project',
          'title' => 'Livelihood Restoration Project | DUS - Dwip Unnayan Society',
          'description' => 'Livelihood restoration project details',
          'keywords' => 'livelihood, restoration, vocational training',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'group-member-insurance-savings-scheme',
          'name' => 'Group Member Insurance/Savings Scheme',
          'title' => 'Group Member Insurance and Savings Scheme | DUS - Dwip Unnayan Society',
          'description' => 'Insurance and savings scheme details',
          'keywords' => 'insurance, savings, social protection',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'social-development-program',
          'name' => 'Social Development Program',
          'title' => 'Social Development Program | DUS - Dwip Unnayan Society',
          'description' => 'Social development program details',
          'keywords' => 'social development, women empowerment, child rights',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'legal-and-human-rights',
          'name' => 'Legal and Human Rights',
          'title' => 'Legal and Human Rights | DUS - Dwip Unnayan Society',
          'description' => 'Legal and human rights program details',
          'keywords' => 'legal aid, human rights, justice',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'watsan',
          'name' => 'WATSAN Program',
          'title' => 'WATSAN Program | DUS - Dwip Unnayan Society',
          'description' => 'WATSAN program details',
          'keywords' => 'water, sanitation, hygiene, WATSAN',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'training-and-other-facilities',
          'name' => 'Training and Other Facilities',
          'title' => 'Training and Other Facilities | DUS - Dwip Unnayan Society',
          'description' => 'Training facilities details',
          'keywords' => 'training, capacity building, skills development',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
        [
          'parent_id' => $projectsPage->id,
          'slug' => 'tourism-and-hospitality',
          'name' => 'Tourism and Hospitality',
          'title' => 'Tourism and Hospitality | DUS - Dwip Unnayan Society',
          'description' => 'Tourism and hospitality program details',
          'keywords' => 'tourism, hospitality, eco-tourism',
          'og_image' => null,
          'template' => 'dynamic',
          'page_type' => 'program',
          'is_published' => true,
          'published_at' => now(),
          'created_by' => null,
          'created_at' => now(),
          'updated_at' => now(),
        ],
      ];

      DB::table('pages')->insert($programChildren);
    }

    $this->command->info('Pages seeded successfully!');
  }
}
